### PR TITLE
Specify compat with DV 2.x

### PR DESCRIPTION
**Pull request by JeroenDeDauw**

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
+2 from my side

**Comment by thiemowmde** [comment]
[I made a bugfix release of the base DataValues component](https://github.com/DataValues/DataValues/releases/tag/2.1.1) and hope this will fix the issue Scrutinizer is running into.

**Comment by JeroenDeDauw** [comment]
I've been ignoring ScurinizerCI reports on Travis for over a year now and would just merge this. You want to wait with merging?

**Comment by thiemowmde** [comment]
It's an actual bug in the 2.x release of the base DataValues component, and this here is a nice opportunity to be sure it's fixed. So yes, I want to wait.

**Pull request merged**
